name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [me_dev]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: any

      - name: Upgrade to Beta Channel with Dart 3.5
        run: |
          flutter channel beta
          flutter upgrade
          flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: |
          flutter config --enable-web
          flutter build web --release --base-href="/ecalunsag_bio/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          user_name: bnrz-clsg
          user_email: e.calunsag12@gmail.com
